### ISSUE TITLE
error: package directory 'Roku by J/R/' does not exist

### ISSUE THREAD

**Issue by bobpaul** [johnrobertmcc/RokuRemote#4]
```
$ python --version
Python 3.10.1
$ python setup.py build
running build
running build_py
error: package directory 'Roku by J/R/' does not exist
```

I think the problem is in setup.py. According to [Python's packaging guidelines](https://packaging.python.org/en/latest/tutorials/packaging-projects/), `name` should only contains letters, numbers, `_` , and `-`. I think the spaces and periods are causing problems.

**Comment by johnrobertmcc** [comment]
Hey! I'm sorry I slept on this for so long. I completely forgot about this project. You are right, the repo I had pushed up was completely wrong. Thank you for the detailed issue log, I pushed up a working repo to main, and added requirements.txt for further clarification

-J.R.
